# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 136dfd9d7f8e234f5d64167eca66e707dd3e32b62e3907970a108adfe5e2774280a795794878bf125be68cfe6b477b091ecbbd95d64ff0bd5a25b8ee5cf86623

test:
  secret_key_base: 203229c33fac484e4996e19bb2d3f8f00c32c664fa9b4cf8592c0ecb74baa9e6a7c83ab4b5a418d266da04c3c6c2be450965f65e85a7190d4606a5a8a87d0d8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
